eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: service-zuul
#zuul:
#  routes:
#    api-a:
#      path: /r/**
#      serviceId: service-ribbo
#    api-b:
#      path: /f/**
#      serviceId: service-feign